services:
  vote:
    image: marvqute/vote:latest
    environment:
      - OPTION_A=${OPTION_A:-Cats}
      - OPTION_B=${OPTION_B:-Dogs}
    depends_on:
     redis:
       condition: service_healthy
    ports:
      - "5000:80"
   
  result:
    image: marvqute/result:latest
    environment:
      - PORT=80
    ports:
      - "8091:80"

  worker:
    image: marvqute/worker:latest
     

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  redis_data:
  db_data: